# fly.toml app configuration file generated for njtransittracker on 2025-11-25T22:20:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'njtransittracker'
primary_region = 'ewr'

[build]
  [build.args]
    GO_VERSION = '1.25'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
